CREATE TABLE imovel (
    id SERIAL NOT NULL,
    titulo VARCHAR(250) NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    condominio DECIMAL(10, 2) NOT NULL,
    iptu DECIMAL(10, 2) NOT NULL,
    area DECIMAL(10, 2) NOT NULL,
    quartos INT NOT NULL,
    salas INT NOT NULL,
    banheiro INT NOT NULL,
    descricao TEXT NOT NULL,
    endereco VARCHAR(250) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    complemento VARCHAR(50),
    bairro VARCHAR(100) NOT NULL,
    cidade VARCHAR(250) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    cep VARCHAR(9) NOT NULL,
    usuario_id INT,
    data_insert DATETIME DEFAULT CURRENT_TIMESTAMP,
    data_update DATETIME on update CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX (endereco),
    INDEX (bairro),
    INDEX (cidade),
    INDEX (estado),
    INDEX (cep),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);